# Copyright (c) 2021-2026 The Regents of the University of Michigan
# Part of spatula, released under the BSD 3-Clause License.

"""Internal helpers for mapping quaternions to symmetry fundamental zones.

Mapping rule used in this module
--------------------------------
For each returned orientation quaternion ``q`` and associated proper-rotation
equivalence set ``S`` (a subset of ``SO(3)`` represented as quaternions),
we construct

``C = { normalize(s ⊗ q) | s in S }``,

where ``⊗`` is quaternion multiplication in ``[w, x, y, z]`` convention and
``normalize`` also enforces the double-cover convention ``w >= 0`` by flipping
sign when needed. The canonical representative is selected as:

1. maximum ``w`` (closest equivalent rotation to the identity),
2. lexicographic tie-break on ``(x, y, z)`` with a small epsilon.

This makes orientation outputs deterministic across all symmetry-equivalent
solutions.
"""

from __future__ import annotations

import numpy as np
from scipy.spatial.transform import Rotation

_DET_EPS = 1e-6
_EQ_EPS = 1e-7
_MAX_OPERATOR_ORDER = 256


def _normalize_wxyz(quaternions: np.ndarray) -> np.ndarray:
    """Normalize quaternions and choose the ``w >= 0`` representative."""
    quaternions = np.asarray(quaternions, dtype=np.float32)
    norms = np.linalg.norm(quaternions, axis=-1, keepdims=True)
    norms = np.where(norms == 0, 1.0, norms)
    normalized = quaternions / norms
    normalized[normalized[..., 0] < 0] *= -1.0
    return normalized


def _quat_multiply_wxyz(lhs: np.ndarray, rhs: np.ndarray) -> np.ndarray:
    """Multiply quaternions in ``[w, x, y, z]`` order."""
    lw, lx, ly, lz = np.moveaxis(lhs, -1, 0)
    rw, rx, ry, rz = np.moveaxis(rhs, -1, 0)
    return np.stack(
        (
            lw * rw - lx * rx - ly * ry - lz * rz,
            lw * rx + lx * rw + ly * rz - lz * ry,
            lw * ry - lx * rz + ly * rw + lz * rx,
            lw * rz + lx * ry - ly * rx + lz * rw,
        ),
        axis=-1,
    )


def _lexicographically_greater(lhs: np.ndarray, rhs: np.ndarray) -> np.ndarray:
    """Return mask where ``lhs`` is lexicographically greater than ``rhs``."""
    delta = lhs[:, 0] - rhs[:, 0]
    greater = delta > _EQ_EPS
    tied = np.abs(delta) <= _EQ_EPS
    for i in range(1, 4):
        delta = lhs[:, i] - rhs[:, i]
        greater = greater | (tied & (delta > _EQ_EPS))
        tied = tied & (np.abs(delta) <= _EQ_EPS)
    return greater


def _choose_canonical_candidates(candidates: np.ndarray) -> np.ndarray:
    """Select canonical quaternions from candidate set.

    Candidates are expected in shape ``(N_candidates, N_quaternions, 4)`` and must
    already be normalized with ``w >= 0``. Selection is by maximal lexicographic
    ``(w, x, y, z)`` order (with epsilon-aware comparisons).
    """
    best = candidates[0].copy()
    for i in range(1, candidates.shape[0]):
        current = candidates[i]
        update = _lexicographically_greater(current, best)
        best[update] = current[update]
    return best


def proper_rotation_quaternions(matrices: np.ndarray) -> np.ndarray:
    """Return proper rotations from matrices as quaternions in ``[w, x, y, z]``.

    Matrices with determinant ``<= _DET_EPS`` are discarded so only proper
    rotations are used for equivalence classes in orientation mapping.
    """
    matrices = np.asarray(matrices, dtype=np.float64).reshape(-1, 3, 3)
    proper = matrices[np.linalg.det(matrices) > _DET_EPS]
    if proper.size == 0:
        proper = np.eye(3, dtype=np.float64).reshape(1, 3, 3)
    quats_xyzw = Rotation.from_matrix(proper).as_quat()
    quats_wxyz = np.column_stack((quats_xyzw[:, 3], quats_xyzw[:, :3]))
    return _normalize_wxyz(quats_wxyz)


def operator_generated_quaternions(operator: np.ndarray) -> np.ndarray:
    """Return proper rotations generated by repeated powers of an operator.

    The sequence starts at identity, multiplies by the input operator until
    returning to identity (or ``_MAX_OPERATOR_ORDER``), keeps only proper
    rotations, deduplicates numerically, and converts to normalized
    ``[w, x, y, z]`` quaternions.
    """
    operator = np.asarray(operator, dtype=np.float64).reshape(3, 3)
    current = np.eye(3, dtype=np.float64)
    proper_powers = [current.copy()]
    for _ in range(1, _MAX_OPERATOR_ORDER + 1):
        current = current @ operator
        if np.linalg.det(current) > _DET_EPS:
            if not any(np.allclose(current, m, atol=1e-6) for m in proper_powers):
                proper_powers.append(current.copy())
        if np.allclose(current, np.eye(3), atol=1e-6):
            break
    return proper_rotation_quaternions(np.asarray(proper_powers))


def map_quaternions_to_fundamental_zone(
    quaternions: np.ndarray, operator_sets: list[np.ndarray]
) -> np.ndarray:
    """Map each quaternion to a deterministic representative in its fundamental zone.

    Parameters
    ----------
    quaternions
        Array shaped ``(N_particles, N_slots, 4)`` in ``[w, x, y, z]`` order.
    operator_sets
        ``operator_sets[i]`` provides the proper-rotation equivalence set for
        slot ``i``. This function left-multiplies each operator in that set onto
        the corresponding quaternion column and selects the canonical candidate
        by the module-level rule (max ``w``, then lexicographic tie-break).
    """
    mapped = _normalize_wxyz(np.asarray(quaternions, dtype=np.float32))
    if mapped.ndim != 3 or mapped.shape[-1] != 4:
        raise ValueError("quaternions must have shape (N, M, 4)")
    if mapped.shape[1] != len(operator_sets):
        raise ValueError("operator_sets length must equal quaternion symmetry dimension")

    for i, operators in enumerate(operator_sets):
        operators = _normalize_wxyz(np.asarray(operators, dtype=np.float32))
        if operators.shape[0] == 1:
            continue
        # Equivalent optima are generated by left-multiplying symmetry operators
        # onto the returned orientation for the corresponding slot.
        candidates = _quat_multiply_wxyz(
            operators[:, np.newaxis, :], mapped[:, i, :][np.newaxis, :, :]
        )
        candidates = _normalize_wxyz(candidates)
        mapped[:, i, :] = _choose_canonical_candidates(candidates)

    return mapped
