name: pgop-rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - scikit-build-core
  - cmake
  - numpy
  - coxeter
  - freud
  - h5py
  - sphinx
  - furo
  - pybind11
  - gxx
  - gcc